### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by dagelf** [claudio-silva/claude-artifact-runner#6]
```
[coenraad@r2t2 ~]$ git clone https://github.com/claudio-silva/claude-artifact-runner.git
Cloning into 'claude-artifact-runner'...
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 134 (delta 29), reused 21 (delta 21), pack-reused 96 (from 1)
Receiving objects: 100% (134/134), 129.51 KiB | 2.49 MiB/s, done.
Resolving deltas: 100% (45/45), done.
[coenraad@r2t2 ~]$ cd claude-artifact-runner/
[coenraad@r2t2 claude-artifact-runner]$ npm install
(node:2033571) ExperimentalWarning: CommonJS module /usr/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

added 426 packages, and audited 427 packages in 4s

70 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[coenraad@r2t2 claude-artifact-runner]$ npm run dev

> artifact-viewer@0.0.0 dev
> vite


  VITE v5.4.8  ready in 147 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
(node:2033697) ExperimentalWarning: CommonJS module /home/coenraad/claude-artifact-runner/node_modules/tailwindcss/lib/lib/load-config.js is loading ES Module /home/coenraad/claude-artifact-runner/tailwind.config.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///home/coenraad/claude-artifact-runner/tailwind.config.js:2
module.exports = {
^

ReferenceError: module is not defined
    at file:///home/coenraad/claude-artifact-runner/tailwind.config.js:2:1
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:367:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:325:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1396:24)
    at Module._compile (node:internal/modules/cjs/loader:1529:5)
    at Object..js (node:internal/modules/cjs/loader:1678:16)
    at Module.load (node:internal/modules/cjs/loader:1315:32)
    at Function._load (node:internal/modules/cjs/loader:1125:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:216:24)
    at Module.require (node:internal/modules/cjs/loader:1337:12)
    at require (node:internal/modules/helpers:139:16)
    at /home/coenraad/claude-artifact-runner/node_modules/tailwindcss/lib/lib/load-config.js:54:27
    at loadConfig (/home/coenraad/claude-artifact-runner/node_modules/tailwindcss/lib/lib/load-config.js:58:6)
    at getTailwindConfig (/home/coenraad/claude-artifact-runner/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:71:116)
    at /home/coenraad/claude-artifact-runner/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:100:92
    at /home/coenraad/claude-artifact-runner/node_modules/tailwindcss/lib/processTailwindFeatures.js:46:11
    at plugins (/home/coenraad/claude-artifact-runner/node_modules/tailwindcss/lib/plugin.js:38:69)
    at LazyResult.runOnRoot (/home/coenraad/claude-artifact-runner/node_modules/postcss/lib/lazy-result.js:329:16)
    at LazyResult.runAsync (/home/coenraad/claude-artifact-runner/node_modules/postcss/lib/lazy-result.js:258:26)
    at LazyResult.async (/home/coenraad/claude-artifact-runner/node_modules/postcss/lib/lazy-result.js:160:30)
    at LazyResult.then (/home/coenraad/claude-artifact-runner/node_modules/postcss/lib/lazy-result.js:404:17)

Node.js v23.1.0
[coenraad@r2t2 claude-artifact-runner]$ 
```

**Comment by claudio-silva** [comment]
Hi
I see you have the latest NodeJS version v23.
This project has been tested with NodeJS up to v18.
It seems the latest NodeJS has introduced some incompatibilities, which I will have to analyze.
Unfortunately, your pull request introduced a new error and did not solve the issue.
I'll have to analyze this issue further.
For the time being, if you need to run this project, I recommend you use NodeJS v18 and npm 10.4
Thank you for taking the time to report this.

**Comment by dagelf** [comment]
I noticed, sorry! Was going to close this as I was busy trying to work through it and realized that the end is not in sight...

**Comment by kcarnold** [comment]
VS Code suggested a couple of fixes, which I applied and it worked. I suspect a version bump on tailwind itself is needed, but this fix got it working well enough for me for now.

For reference, here's what `tailwind.config.js` looks like on my working local copy:

```js
/** @type {import('tailwindcss').Config} */
export const darkMode = ["class"];
export const content = [
  './pages/**/*.{ts,tsx}',
  './components/**/*.{ts,tsx}',
  './app/**/*.{ts,tsx}',
  './src/**/*.{ts,tsx}',
];
export const prefix = "";
export const theme = {
  container: {
    center: true,
    padding: "2rem",
    screens: {
      "2xl": "1400px",
    },
  },
  extend: {
    colors: {
      border: "hsl(var(--border))",
      input: "hsl(var(--input))",
      ring: "hsl(var(--ring))",
      background: "hsl(var(--background))",
      foreground: "hsl(var(--foreground))",
      primary: {
        DEFAULT: "hsl(var(--primary))",
        foreground: "hsl(var(--primary-foreground))",
      },
      secondary: {
        DEFAULT: "hsl(var(--secondary))",
        foreground: "hsl(var(--secondary-foreground))",
      },
      destructive: {
        DEFAULT: "hsl(var(--destructive))",
        foreground: "hsl(var(--destructive-foreground))",
      },
      muted: {
        DEFAULT: "hsl(var(--muted))",
        foreground: "hsl(var(--muted-foreground))",
      },
      accent: {
        DEFAULT: "hsl(var(--accent))",
        foreground: "hsl(var(--accent-foreground))",
      },
      popover: {
        DEFAULT: "hsl(var(--popover))",
        foreground: "hsl(var(--popover-foreground))",
      },
      card: {
        DEFAULT: "hsl(var(--card))",
        foreground: "hsl(var(--card-foreground))",
      },
    },
    borderRadius: {
      lg: "var(--radius)",
      md: "calc(var(--radius) - 2px)",
      sm: "calc(var(--radius) - 4px)",
    },
    keyframes: {
      "accordion-down": {
        from: { height: "0" },
        to: { height: "var(--radix-accordion-content-height)" },
      },
      "accordion-up": {
        from: { height: "var(--radix-accordion-content-height)" },
        to: { height: "0" },
      },
    },
    animation: {
      "accordion-down": "accordion-down 0.2s ease-out",
      "accordion-up": "accordion-up 0.2s ease-out",
    },
  },
};
import tailwindcssAnimate from "tailwindcss-animate";

export const plugins = [tailwindcssAnimate];
```

**Comment by claudio-silva** [comment]
Hi @kcarnold, thanks for your fix!

Your contribution prompted me to finally tackle this issue. I used your file as a starting point, and instead of just merging it and calling it a day, I investigated the root cause of the incompatibility with the latest Node.js and how to fix it. I like to understand what I'm doing and why.

After fixing this, I also tested the project with multiple Node.js versions to ensure it works on older versions as well. I determined that it is compatible with versions down to v15, which should be sufficient for most users.

**Comment by kcarnold** [comment]
Great, that's exactly what I'd hoped. I didn't submit my fix as a PR because I hadn't investigated the root cause so my kludge wasn't merge-worthy. I'm glad the fix was even simpler than I'd been led to expect by, ironically, asking Claude.ai.
